SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP SCHEMA IF EXISTS `swen` ;
CREATE SCHEMA IF NOT EXISTS `swen` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `swen` ;

source tables/users.sql;
source tables/magazines.sql;
source tables/feeds.sql;
source tables/entities.sql;
source tables/magazines_has_feeds.sql;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
